version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20

  build:
    commands:
      - cd site && npm install && npm install --include=dev --legacy-peer-deps && npm run docker:build:prod
      - mkdir artifacts && cp -r dist/site/browser/* artifacts/

artifacts:
  files:
    - '**/*'
  base-directory: artifacts
