version: "3.8"
   
services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev-runner
    ports:
      - "4200:4200"
    container_name: "website"
    volumes:
      - ./site/src/:/code/src/
