services:
  lambda-tracker:
    build:
      context: .
      dockerfile: Dockerfile.lambda
    ports:
      - "9000:8080"
    volumes:
      - ./:/usr/app
      - node_modules:/usr/app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    platform: linux/amd64
  
  test:
    build:
      context: .
      dockerfile: Dockerfile.lambda
    working_dir: /usr/app
    volumes:
      - ./:/usr/app
      - node_modules:/usr/app/node_modules
    env_file:
      - .env
    entrypoint: ["/bin/sh", "-c", "npm install && npm test"]

volumes:
  node_modules:
