name: Deploy Website to S3

on:
  push:
    branches:
      - main
    paths:
      - 'site/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_IAM_ROLE }}
          aws-region: us-east-1

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Build Website
        run: |
          cd site
          npm install
          npm install --include=dev --legacy-peer-deps
          npm run docker:build:prod

      - name: Deploy to S3
        run: |
          aws s3 sync ./site/dist/site/browser s3://${{ secrets.S3_BUCKET_NAME }}